youtube_key: YOUR_YOUTUBE_APIKEY
playlist_id: PLAYLIST_ID
chunk_size: 50
aws:
  access_key_id: YOUR_ACCESS_KEY_ID
  secret_access_key: YOUR_SECRET_ACCESS_KEY
  region: YOUR_AWS_REGION
  s3:
    bucket: YOUR_S3_BUCKET
max_retries: 3
email:
  email: YOUR_EMAIL
  app_password: YOUR_EMAIL_APP_PASSWORD
  smtp_server: SMTP_SERVER
  smtp_server_port: SMTP_SERVER_PORT
requester_email: PLAYLIST_DOWNLOAD_REQUESTER_EMAIL